# Generated by Django 3.0.2 on 2020-01-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='title')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('release_time', models.DateTimeField(verbose_name='release_time')),
                ('modify_time', models.DateTimeField(verbose_name='modify_time')),
                ('content', models.TextField(verbose_name='content')),
                ('link', models.CharField(max_length=256, verbose_name='link')),
                ('visible', models.BooleanField(verbose_name='visible')),
                ('categories', models.ManyToManyField(to='post.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('release_time', models.DateTimeField(verbose_name='release_time')),
                ('content', models.TextField(verbose_name='content')),
                ('visible', models.BooleanField(verbose_name='visible')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('replyTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Comment')),
            ],
        ),
    ]
