# Generated by Django 3.0.2 on 2020-01-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading',
            field=models.IntegerField(default=0, verbose_name='reading'),
        ),
    ]
