# Generated by Django 3.0.2 on 2020-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modify_time',
            field=models.TimeField(verbose_name='modify_time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_time',
            field=models.TimeField(verbose_name='release_time'),
        ),
    ]
