# Generated by Django 3.0.2 on 2020-01-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200112_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='release_time',
            field=models.DateTimeField(default='2020-01-12 00:00:00', verbose_name='release_time'),
            preserve_default=False,
        ),
    ]
